name: Setsuna
favicon: null
layout_spectrum: 0.7567287194542587
typography_spectrum: 0.8044315935112536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.046832425985485315
  lightness: 0.5522276370320469
  saturation: 0.45971946767531335
  rhythmicContrast: 0.8457681564614177
purpose: []
