name: Setsuna
favicon: null
layout_spectrum: 0.27546
typography_spectrum: 0.41378
title: Setsuna
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9d9d9d'
    - '#c8c8c8'
    - '#00a38e'
    - '#54c5b8'
  brandStrength: 0
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
